// Importing the createSlice function from Redux Toolkit, which helps in creating Redux slices
import { createSlice } from "@reduxjs/toolkit";

// Creating a slice for user state management
const userSlice = createSlice({
  // Slice name, used in action types and for debugging
  name: "user",
  
  // Initial state of the slice, containing userInfo which is initially set to null
  initialState: {
    userInfo: null,
  },

  // Reducers for handling state updates
  reducers: {
    // Action to set user information in the state
    setUser: (state, action) => {
      // Updating the userInfo with the payload from the action
      state.userInfo = action.payload;
    },
    
    // Action to clear user information from the state
    clearUser: (state) => {
      // Resetting userInfo back to null
      state.userInfo = null;
    },
  },
});

// Exporting the actions generated by createSlice for use in components
export const { setUser, clearUser } = userSlice.actions;

// Exporting the reducer function to be used in the store
export default userSlice.reducer;